### ISSUE TITLE
Brightness control in Plasma 5.25 is broken

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#117]
Hi, it seems plasma 5.25 has broken the screen brightness control for certain laptops, making impossible to increase it beyond like 20%. There seems to be a fix in powerdevil. Could you bring this patch to your copr? This makes my (and many other's) laptop essentially unusable.

This seems to be the commit fixing the bug: https://invent.kde.org/plasma/powerdevil/-/commit/2ebe655d220c9167b66893a823b2fff2e2b8a531

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/4545442

**Comment by ZaWertun** [comment]
Try powerdevil-5.25.0-2, issue should be fixed.

**Comment by marco-calautti** [comment]
I still cannot see the new package, even after a dnf update --refresh

**Comment by marco-calautti** [comment]
I installed the rpm manually, and the issue is fixed! Thanks!

**Comment by ZaWertun** [comment]
> I still cannot see the new package, even after a dnf update --refresh

Ususally it takes some time after I refresh repo metadata.
