### ISSUE TITLE
Upgrade Problem  kde-connect-libs-21.12.2-1.fc35.x86_64

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#94]
sudo dnf upgrade --refresh --best --allowerasing

Problem: problem with installed package kde-connect-libs-21.12.2-1.fc35.x86_64
  - cannot install the best update candidate for package kde-connect-libs-21.12.2-1.fc35.x86_64
  - package kde-connect-libs-21.12.2-1.fc35.x86_64 requires libKF5PulseAudioQt.so.2()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-qt-1.2-6.fc35.x86_64
  - cannot install both pulseaudio-qt-1.3-2.fc35.x86_64 and pulseaudio-qt-1.2-6.fc35.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/3499485

**Comment by ZaWertun** [comment]
New build for kde-connect, should fix this issue.

**Comment by marco-calautti** [comment]
I still have the issue on my machine. Did sudo dnf update --refresh

**Comment by ZaWertun** [comment]
Build is ready - you could do `dnf up --refresh`.
Thanks for reporting the issue!

**Comment by architectlin** [comment]
Thanks your Fix
